theme = "custom"

[editor]
line-number = "relative"
mouse = false
cursorline = true

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
