[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
auto-format = true
language-servers = ["emmet-lsp", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "markdown"
auto-format = true
language-servers = ["marksman"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "tsx"
language-servers = ["emmet-lsp", "typescript-language-server", "tailwindcss-ls"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
